version: '3'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./files:/app/files
    environment:
      - TELEGRAM_BOT_TOKEN=YOUR_TELEGRAM_BOT_TOKEN
      - GROUP_ID=YOUR_GROUP_ID
    restart: always

  caddy:
    image: caddy
    ports:
      - 30080:80
    volumes:
      - ./files:/var/www/html/files
    restart: always
